# Generated by Django 4.2.23 on 2025-10-01 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Created', max_length=60)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.tasks')),
            ],
            options={
                'verbose_name': 'SubTask',
                'verbose_name_plural': 'SubTask',
                'ordering': ['id'],
            },
        ),
    ]
