# Generated by Django 4.2.23 on 2025-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='main_task',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='name',
            new_name='subtask_type',
        ),
        migrations.AddField(
            model_name='subtask',
            name='dataset_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
