# Generated by Django 4.2.23 on 2026-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_dataset_id_subtask_dataset_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Running', 'Running'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Error', 'Error')], default='Created', max_length=60),
        ),
    ]
