# Generated by Django 4.2.23 on 2026-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_subtask_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['main_task', 'subtask_type', 'dataset_path'], name='idx_subtask_lookup'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['user'], name='idx_tasks_user'),
        ),
    ]
