# Generated by Django 4.2.23 on 2026-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_subtask_idx_subtask_lookup_tasks_idx_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='slurm_missing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
