# Generated by Django 6.1 on 2026-08-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_tasks_slurm_missing_since'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['userpath'], name='idx_tasks_userpath'),
        ),
    ]
